### ISSUE TITLE
Org2html.sh not found

### ISSUE THREAD

**Issue by jbz-dev** [ConradBailey/org-site#2]
Still here with another issue :)

With absolute location as arguments `org-site.py` works but throw an error about a missing `org2html.sh`.

Which in fact is in the same directory.

**Comment by ConradBailey** [comment]
This is occurring because `org2html.sh` is not in your `PATH` environment variable. I rely on the `PATH` because I didn't feel like learning how to officially package this project at the time. I'll make it such that `org-site.py` looks for `org2html.sh` beside itself, as you intuited. Later, packaging would be the preferred way to negotiate this relationship.

**Comment by ConradBailey** [comment]
@Bridouz Updates should have fixed this; let me know if it worked for you.

**Comment by jbz-dev** [comment]
It works, thanks.
